name: Main Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Build
        run: echo "Hello Github!"