name: Main Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Jar
        env:
          ORG_GRADLE_PROJECT_BUILD_NUMBER: ${{ github.run_number }}
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: todo-list
          path: build/libs/*
